### ISSUE TITLE
Overwriting EXPECTED_RESULTS

### ISSUE THREAD

**Issue by sspasweden** [freol35241/pytest-pinned#11]
Idea: EXPECTED_RESULTS gets overwritten only when it is requested by pinned-rewrite or pinned-update (not pinned-path).

Instead of https://github.com/freol35241/pytest-pinned/blob/master/pytest_pinned.py#L49,
"if EXPECTED_RESULTS and (rewrite or update):"

**Comment by freol35241** [comment]
Hi,
If this is a bug report, please provide an explanation as to **why** it should be considered as such.
